#!/bin/sh

set -x -e

ZNCPASS=`pee -p znc`

NETWORKS="elynx freenode furnet"

for net in $NETWORKS; do
    IIPASS="Kooda/$net:$ZNCPASS" ii -i /tmp/irc -s localhost -d "$net" -p 8350 -n Kooda -k IIPASS &
done
